"use client";

import { useState, useRef, SetStateAction } from "react";
import { maskText } from "@/utilities/mask";
import { Label } from "@/components/ui/label";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { removeCommaBeforeAnd } from "@/utilities/comma";

export default function Home() {
  // state for original text
  const [originalText, setOriginalText] = useState("");

  // state for masked text
  const [maskedText, setMaskedText] = useState("");

  // state to track button text
  const [buttonText, setButtonText] = useState("Mask Text");

  // reference to "Masked Text" textarea
  const maskedTextAreaRef = useRef<HTMLTextAreaElement | null>(null);

  const handleMaskText = () => {
    if (buttonText === "Mask Text") {
      // remove any commas appearing right before the word "and"
      const textWithoutCommaBeforeAnd = removeCommaBeforeAnd(originalText);

      // mask the processed text with Cyrillic characters
      const finalText = maskText(textWithoutCommaBeforeAnd);

      // render the masked text in the "Masked Text" textarea
      setMaskedText(finalText);

      // update the state of the button text
      setButtonText("Copy Text");
    } else if (buttonText === "Copy Text") {
      // copy text from the "Masked Text" textarea to the clipboard
      maskedTextAreaRef.current?.select();
      document.execCommand("copy");

      // log the masked text to the console (for debugging)
      console.log(`Masked text: ${maskedText}`);
    }
  };

  // listen to changes happening to original text
  const handleOriginalTextChange = (e: {
    target: { value: SetStateAction<string> };
  }) => {
    setOriginalText(e.target.value);

    // reset button text to "Mask Text"
    setButtonText("Mask Text");
  };

  return (
    <main className="flex flex-col h-screen">
      {/* Header */}
      <header className="w-full top-0 left-0 flex justify-between p-5">
        <div>
          <h1 className="font-bold">MaskGPT</h1>
        </div>
        <div>
          <a href="/about" className="px-8">
            About
          </a>
          <a
            href="https://github.com/ravi-aratchige/maskgpt"
            target="_blank"
            rel="noopener"
          >
            Github
          </a>
        </div>
      </header>

      {/* Page Content */}

      <section className="flex-grow">
        {/* Introduction */}
        <section className="flex justify-center pb-16 pt-24 px-8">
          <p className="text-center">
            Disguise text taken from the Internet or generated by AI to avoid
            detection by plagiarism checkers like Turnitin!
          </p>
        </section>

        {/* Text areas */}
        <section className="flex justify-center px-8">
          {/* Original text */}
          <div className="grid w-full gap-1.5 px-2">
            <div className="flex justify-between">
              <Label htmlFor="original-text">Original Text</Label>
            </div>
            <Textarea
              placeholder="Type your original text here."
              id="original-text"
              className="h-80 resize-none"
              value={originalText}
              onChange={handleOriginalTextChange}
            />
          </div>
          {/* Masked text */}
          <div className="grid w-full gap-1.5 px-2">
            <div className="flex justify-between">
              <Label htmlFor="masked-text">Masked Text</Label>
            </div>
            <Textarea
              placeholder="The masked text will be generated here."
              id="masked-text"
              className="h-80 resize-none"
              value={maskedText}
              readOnly
              ref={maskedTextAreaRef}
            />
          </div>
        </section>

        {/* "Mask Text" Button */}
        <div className="flex flex-col items-center justify-between p-6">
          <Button onClick={handleMaskText}>{buttonText}</Button>
        </div>
      </section>

      {/* Footer */}
      <footer className="bottom-0 left-0 flex justify-center w-full py-6">
        <p>
          Made with ❤️ by{" "}
          <a
            href="https://github.com/ravi-aratchige"
            className="hover:font-bold"
          >
            Ravindu Aratchige
          </a>
        </p>
      </footer>
    </main>
  );
}
