"use client";

// import Image from "next/image";
import { useState } from "react";
import { maskText } from "@/utilities/mask";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";

export default function Home() {
  // state for original text
  const [originalText, setOriginalText] = useState("");
  // state for masked text
  const [maskedText, setMaskedText] = useState("");

  // handle mask button click
  const handleMaskText = () => {
    // process original text using maskText function
    const processedText = maskText(originalText);
    // set masked text state
    setMaskedText(processedText);
  };

  return (
    <main className="flex flex-col h-screen">
      {/* Header */}
      <header className="w-full top-0 left-0 flex justify-between p-5">
        <div>
          <h1 className="font-bold">MaskGPT</h1>
        </div>
        <div>
          <a href="/about" className="px-8">
            About
          </a>
          <a
            href="https://github.com/ravi-aratchige/maskgpt"
            target="_blank"
            rel="noopener"
          >
            Github
          </a>
        </div>
      </header>

      {/* Page Content */}

      <section className="flex-grow">
        {/* Introduction */}
        <section className="flex justify-center pb-16 pt-24 px-8">
          <p className="text-center">
            Disguise text taken from the Internet or generated by AI to avoid
            detection by plagiarism checkers like Turnitin!
          </p>
        </section>

        {/* Text areas */}
        <section className="flex justify-center px-8">
          {/* Original text */}
          <div className="grid w-full gap-1.5 px-2">
            <Label htmlFor="original-text">Original Text</Label>
            <Textarea
              placeholder="Type your original text here."
              id="original-text"
              className="h-80 resize-none"
              value={originalText}
              onChange={(e) => setOriginalText(e.target.value)}
            />
          </div>
          {/* Masked text */}
          <div className="grid w-full gap-1.5 px-2">
            <Label htmlFor="masked-text">Masked Text</Label>
            <Textarea
              placeholder="The masked text will be generated here."
              id="masked-text"
              className="h-80 resize-none"
              value={maskedText}
              readOnly
            />
          </div>
        </section>

        {/* "Mask Text" Button */}
        <div className="flex flex-col items-center justify-between p-6">
          <Button onClick={handleMaskText}>Mask Text</Button>
        </div>
      </section>

      {/* Footer */}
      <footer className="bottom-0 left-0 flex justify-center w-full py-6">
        <p>
          Made with ❤️ by{" "}
          <a
            href="https://github.com/ravi-aratchige"
            className="hover:font-bold"
          >
            Ravindu Aratchige
          </a>
        </p>
      </footer>
    </main>
  );
}
